### PR TITLE
Travis CI: choco install vcpython27 workaround

### PR DESCRIPTION
**Pull request by cclauss**
__choco install python2 vcredist2008 ; choco install --ignore-dependencies vcpython27__ is the workaround to prevent this formula from installing __dotnet3.5__ on top of __dotnet4.6.2__ on Travis CI Windows environments.
```
The install of dotnet3.5 was NOT successful.
Error while running 'C:\ProgramData\chocolatey\lib\DotNet3.5\Tools\ChocolateyInstall.ps1'.
See log for details.
```
https://blog.travis-ci.com/2018-10-11-windows-early-release
https://docs.travis-ci.com/user/reference/windows
https://chocolatey.org/packages/vcpython27

### CODE REVIEW

**Comment by gep13** [comment]
@cclauss be careful using that option. It is going to apply to all the packages passed to the install command, not just the one that you have placed it after.  If you only want to ignore dependencies on a single package, I would suggest having separate install commands.

**Comment by fredrikaverpil** [comment]
Hey @cclauss, thanks for the patch.

I realized I had turned off Travis CI for this repository for some reason. Would you mind pushing a minor change such as adding whitespace to the .yml and then reverting it, in order to trigger Travis?

I can merge once Travis builds successfully and update the choco package.

**Comment by fredrikaverpil** [comment]
Actually, would you mind adding this optional functionality to the [README.md](https://github.com/fredrikaverpil/vcpython27/blob/master/README.md) instead (this will trigger Travis CI).

**Comment by fredrikaverpil** [comment]
@cclauss Never mind!
I don't even have Travis CI enabled for this repo!
Too early in the morning here...

**Comment by fredrikaverpil** [comment]
Looking good to me! Thank you @cclauss

**Pull request merged**
